<?php


namespace App\Pages\Blocks\Text;


use App\Fields\Color;
use App\Fields\Icon;
use App\Fields\Markdown;
use App\Fields\Panel;
use App\Fields\Row;
use App\Fields\Select;
use App\Fields\Text;
use App\Pages\Blocks\Block;

class TextIconBlock extends Block
{
    private static $icons = [
        'zondicon-add-outline',
        'zondicon-add-solid',
        'zondicon-adjust',
        'zondicon-airplane',
        'zondicon-album',
        'zondicon-align-center',
        'zondicon-align-justified',
        'zondicon-align-left',
        'zondicon-align-right',
        'zondicon-anchor',
        'zondicon-announcement',
        'zondicon-apparel',
        'zondicon-arrow-down',
        'zondicon-arrow-left',
        'zondicon-arrow-outline-down',
        'zondicon-arrow-outline-left',
        'zondicon-arrow-outline-right',
        'zondicon-arrow-outline-up',
        'zondicon-arrow-right',
        'zondicon-arrow-thick-down',
        'zondicon-arrow-thick-left',
        'zondicon-arrow-thick-right',
        'zondicon-arrow-thick-up',
        'zondicon-arrow-thin-down',
        'zondicon-arrow-thin-left',
        'zondicon-arrow-thin-right',
        'zondicon-arrow-thin-up',
        'zondicon-arrow-up',
        'zondicon-artist',
        'zondicon-at-symbol',
        'zondicon-attachment',
        'zondicon-backspace',
        'zondicon-backward',
        'zondicon-backward-step',
        'zondicon-badge',
        'zondicon-battery-full',
        'zondicon-battery-half',
        'zondicon-battery-low',
        'zondicon-beverage',
        'zondicon-block',
        'zondicon-bluetooth',
        'zondicon-bolt',
        'zondicon-book-reference',
        'zondicon-bookmark',
        'zondicon-bookmark-outline',
        'zondicon-bookmark-outline-add',
        'zondicon-bookmark_copy_2',
        'zondicon-bookmark_copy_3',
        'zondicon-border-all',
        'zondicon-border-bottom',
        'zondicon-border-horizontal',
        'zondicon-border-inner',
        'zondicon-border-left',
        'zondicon-border-none',
        'zondicon-border-outer',
        'zondicon-border-right',
        'zondicon-border-top',
        'zondicon-border-vertical',
        'zondicon-box',
        'zondicon-brightness-down',
        'zondicon-brightness-up',
        'zondicon-browser-window',
        'zondicon-browser-window-new',
        'zondicon-browser-window-open',
        'zondicon-bug',
        'zondicon-buoy',
        'zondicon-calculator',
        'zondicon-calendar',
        'zondicon-camera',
        'zondicon-chart',
        'zondicon-chart-bar',
        'zondicon-chart-pie',
        'zondicon-chat-bubble-dots',
        'zondicon-checkmark',
        'zondicon-checkmark-outline',
        'zondicon-cheveron-down',
        'zondicon-cheveron-left',
        'zondicon-cheveron-outline-down',
        'zondicon-cheveron-outline-left',
        'zondicon-cheveron-outline-right',
        'zondicon-cheveron-outline-up',
        'zondicon-cheveron-right',
        'zondicon-cheveron-up',
        'zondicon-clipboard',
        'zondicon-close',
        'zondicon-close-outline',
        'zondicon-close-solid',
        'zondicon-cloud',
        'zondicon-cloud-upload',
        'zondicon-code',
        'zondicon-coffee',
        'zondicon-cog',
        'zondicon-color-palette',
        'zondicon-compose',
        'zondicon-computer-desktop',
        'zondicon-computer-laptop',
        'zondicon-conversation',
        'zondicon-copy',
        'zondicon-credit-card',
        'zondicon-currency-dollar',
        'zondicon-dashboard',
        'zondicon-date-add',
        'zondicon-dial-pad',
        'zondicon-directions',
        'zondicon-document',
        'zondicon-document-add',
        'zondicon-dots-horizontal-double',
        'zondicon-dots-horizontal-triple',
        'zondicon-download',
        'zondicon-duplicate',
        'zondicon-edit-copy',
        'zondicon-edit-crop',
        'zondicon-edit-cut',
        'zondicon-edit-pencil',
        'zondicon-education',
        'zondicon-envelope',
        'zondicon-exclamation-outline',
        'zondicon-exclamation-solid',
        'zondicon-explore',
        'zondicon-factory',
        'zondicon-fast-forward',
        'zondicon-fast-rewind',
        'zondicon-film',
        'zondicon-filter',
        'zondicon-flag',
        'zondicon-flashlight',
        'zondicon-folder',
        'zondicon-folder-outline',
        'zondicon-folder-outline-add',
        'zondicon-format-bold',
        'zondicon-format-font-size',
        'zondicon-format-italic',
        'zondicon-format-text-size',
        'zondicon-format-underline',
        'zondicon-forward',
        'zondicon-forward-step',
        'zondicon-gift',
        'zondicon-globe',
        'zondicon-hand-stop',
        'zondicon-hard-drive',
        'zondicon-headphones',
        'zondicon-heart',
        'zondicon-home',
        'zondicon-hot',
        'zondicon-hour-glass',
        'zondicon-inbox',
        'zondicon-inbox-check',
        'zondicon-inbox-download',
        'zondicon-inbox-full',
        'zondicon-indent-decrease',
        'zondicon-indent-increase',
        'zondicon-information-outline',
        'zondicon-information-solid',
        'zondicon-key',
        'zondicon-keyboard',
        'zondicon-layers',
        'zondicon-library',
        'zondicon-light-bulb',
        'zondicon-link',
        'zondicon-list',
        'zondicon-list-add',
        'zondicon-list-bullet',
        'zondicon-load-balancer',
        'zondicon-location',
        'zondicon-location-current',
        'zondicon-location-food',
        'zondicon-location-gas-station',
        'zondicon-location-hotel',
        'zondicon-location-marina',
        'zondicon-location-park',
        'zondicon-location-restroom',
        'zondicon-location-shopping',
        'zondicon-lock-closed',
        'zondicon-lock-open',
        'zondicon-map',
        'zondicon-menu',
        'zondicon-mic',
        'zondicon-minus-outline',
        'zondicon-minus-solid',
        'zondicon-mobile-devices',
        'zondicon-mood-happy-outline',
        'zondicon-mood-happy-solid',
        'zondicon-mood-neutral-outline',
        'zondicon-mood-neutral-solid',
        'zondicon-mood-sad-outline',
        'zondicon-mood-sad-solid',
        'zondicon-mouse',
        'zondicon-music-album',
        'zondicon-music-artist',
        'zondicon-music-notes',
        'zondicon-music-playlist',
        'zondicon-navigation-more',
        'zondicon-network',
        'zondicon-news-paper',
        'zondicon-notification',
        'zondicon-notifications',
        'zondicon-notifications-outline',
        'zondicon-paste',
        'zondicon-pause',
        'zondicon-pause-outline',
        'zondicon-pause-solid',
        'zondicon-pen-tool',
        'zondicon-phone',
        'zondicon-photo',
        'zondicon-php-elephant',
        'zondicon-pin',
        'zondicon-play',
        'zondicon-play-outline',
        'zondicon-playlist',
        'zondicon-plugin',
        'zondicon-portfolio',
        'zondicon-printer',
        'zondicon-pylon',
        'zondicon-question',
        'zondicon-queue',
        'zondicon-radar',
        'zondicon-radar_copy_2',
        'zondicon-radio',
        'zondicon-refresh',
        'zondicon-reload',
        'zondicon-reply',
        'zondicon-reply-all',
        'zondicon-repost',
        'zondicon-save-disk',
        'zondicon-screen-full',
        'zondicon-search',
        'zondicon-send',
        'zondicon-servers',
        'zondicon-share',
        'zondicon-share-01',
        'zondicon-share-alt',
        'zondicon-shield',
        'zondicon-shopping-cart',
        'zondicon-show-sidebar',
        'zondicon-shuffle',
        'zondicon-stand-by',
        'zondicon-star-full',
        'zondicon-station',
        'zondicon-step-backward',
        'zondicon-step-forward',
        'zondicon-stethoscope',
        'zondicon-store-front',
        'zondicon-stroke-width',
        'zondicon-subdirectory-left',
        'zondicon-subdirectory-right',
        'zondicon-swap',
        'zondicon-tablet',
        'zondicon-tag',
        'zondicon-target',
        'zondicon-text-box',
        'zondicon-text-decoration',
        'zondicon-thermometer',
        'zondicon-thumbs-down',
        'zondicon-thumbs-up',
        'zondicon-ticket',
        'zondicon-time',
        'zondicon-timer',
        'zondicon-tools_copy',
        'zondicon-translate',
        'zondicon-trash',
        'zondicon-travel',
        'zondicon-travel-bus',
        'zondicon-travel-car',
        'zondicon-travel-case',
        'zondicon-travel-taxi-cab',
        'zondicon-travel-train',
        'zondicon-travel-walk',
        'zondicon-trophy',
        'zondicon-tuning',
        'zondicon-upload',
        'zondicon-usb',
        'zondicon-user',
        'zondicon-user-add',
        'zondicon-user-group',
        'zondicon-user-solid-circle',
        'zondicon-user-solid-square',
        'zondicon-vector',
        'zondicon-video-camera',
        'zondicon-view-carousel',
        'zondicon-view-column',
        'zondicon-view-hide',
        'zondicon-view-list',
        'zondicon-view-show',
        'zondicon-view-tile',
        'zondicon-volume-down',
        'zondicon-volume-mute',
        'zondicon-volume-off',
        'zondicon-volume-up',
        'zondicon-wallet',
        'zondicon-watch',
        'zondicon-window',
        'zondicon-window-new',
        'zondicon-window-open',
        'zondicon-wrench',
        'zondicon-yin-yang',
        'zondicon-zoom-in',
        'zondicon-zoom-out',
    ];

    public function fields(): array
    {
        return [
            new Panel('Text', [
                new Row([
                    Text::make('Heading', 'data.heading')
                        ->rules([
                            'required',
                            'string',
                            'max:100',
                        ]),

                    Select::make('Heading type', 'data.heading_type')
                        ->options([
                            'h1' => 'Heading 1',
                            'h2' => 'Heading 2',
                            'h3' => 'Heading 3',
                            'h4' => 'Heading 4',
                            'h5' => 'Heading 5',
                            'normal' => 'Normal',
                            'hidden' => 'Hidden',
                        ])
                        ->defaultTo('h1'),

                    Select::make('Alignment', 'data.alignment')
                        ->options([
                            'left' => 'Left',
                            'center' => 'Center',
                            'right' => 'Right'
                        ])
                        ->defaultTo('left'),
                ]),

                Markdown::make('Content', 'data.content'),
            ]),

            new Panel('Icon', [
                Icon::make('Icon', 'data.icon')
                    ->icons(static::$icons)
                    ->rules(['required']),

                Color::make('Color', 'data.icon_color')
                    ->rules(['required'])
                    ->defaultTo('#000'),

                Select::make('Image position', 'data.image_position')
                    ->options([
                        'above_center' => 'Above, centered',
                        'below_center' => 'Below, centered',
                        'beside_left' => 'Beside, left',
                        'beside_right' => 'Beside, right',
                    ])
                    ->defaultTo('above_center'),
            ]),


        ];
    }


}