<?php


namespace App\Fields;


class Icon extends Field
{
    protected function getDefaultRules()
    {
        return [];
    }

    protected function append(): array
    {
        return parent::append(); // TODO: Change the autogenerated stub
    }


}